return {
	git = {
		added = "",
		branch = "󰘬 ",
		conflict = "",
		deleted = "",
		ignored = "",
		modified = "",
		renamed = " ",
		staged = "S",
		unstaged = "U",
		untracked = "",
	},

	kind_icons = {
		Array = "",
		Boolean = "",
		Class = "󰠱",
		Color = "󰏘",
		Constant = "",
		Constructor = "",
		Enum = "",
		EnumMember = "",
		Event = "",
		Field = "",
		File = "",
		Folder = "󰉋",
		Function = "",
		Interface = "",
		Keyword = "󰌆",
		Method = "",
		Misc = "",
		Module = "󰕳",
		Namespace = "",
		Null = "",
		Number = "󰎠",
		Object = "",
		Operator = "󰆕",
		Package = "",
		Property = "",
		Reference = "",
		Snippet = "󰆐",
		String = "󰉿",
		Struct = "",
		Text = "󰉿",
		TypeParameter = " ",
		Unit = "",
		Value = "",
		Variable = "󰀫",
	},

	neotree = {
		default = "",
		folder_closed = "",
		folder_empty = "󰜌",
		folder_open = "",
		expander_collapsed = "",
		expander_expanded = "",
	},

	signs = {
		Error = "󰅙 ",
		Hint = "󰌵",
		Info = "",
		Warn = " ",
	},

	telescope = {
		find = "   ",
		select = " ",
	},
}
